### ISSUE TITLE
error about mnist data shape

### ISSUE THREAD

**Issue by SpiritBear000** [corenel/pytorch-adda#21]
when i run 'main.py', i got following error.

`Traceback (most recent call last):
 
 File "Domain_Adaption/pytorch-adda/main.py", line 41, in <module>
    src_encoder, src_classifier, src_data_loader)
  File "Domain_Adaption/pytorch-adda/core/pretrain.py", line 32, in train_src
    for step, (images, labels) in enumerate(data_loader):
  File "/envs/***/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File /envs/****/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/envs/****/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 95, in __getitem__
    img = self.transform(img)
  File "/envs/****/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/envs/****/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/envs/****/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: output with shape [1, 28, 28] doesn't match the broadcast shape [3, 28, 28]
`

**Comment by Dr-Zhou** [comment]
I also meet 

> when i run 'main.py', i got following error.
> 
> `Traceback (most recent call last):
> 
> File "Domain_Adaption/pytorch-adda/main.py", line 41, in 
> src_encoder, src_classifier, src_data_loader)
> File "Domain_Adaption/pytorch-adda/core/pretrain.py", line 32, in train_src
> for step, (images, labels) in enumerate(data_loader):
> File "/envs/_**/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in **next** batch = self.collate_fn([self.dataset[i] for i in indices]) File /envs/**__/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in batch = self.collate_fn([self.dataset[i] for i in indices]) File "/envs/__**/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 95, in **getitem** img = self.transform(img) File "/envs/**__/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 60, in **call** img = t(img) File "/envs/__**/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 163, in **call** return F.normalize(tensor, self.mean, self.std, self.inplace) File "/envs/**_*/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 208, in normalize
> tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
> RuntimeError: output with shape [1, 28, 28] doesn't match the broadcast shape [3, 28, 28]
> `

I also meet the same problem。How do you solve it ?

**Comment by mvivekc** [comment]
Seems like same as #20 but with more details. Also, i'm facing the same error.

**Comment by Dr-Zhou** [comment]
> Seems like same as #20 but with more details. Also, i'm facing the same error.

you can use this solution。https://stackoverflow.com/questions/56033173/kmnist-runtimeerror-output-with-shape-1-28-28-doesnt-match-the-broadcast

**Comment by mvivekc** [comment]
@Dr-Zhou Do you mean, solution can be provided on Stackoverflow? OR the solution is already there? -- there are no answers for the Question.

**Comment by Dr-Zhou** [comment]
you can see this。https://blog.csdn.net/weixin_43159148/article/details/88778371。but  I also meet other problem

**Comment by mvivekc** [comment]
Downgrading torch and torchvision to 0.2.0 and 0.2.1 solved this issue for me.

**Comment by MiZhiLiang** [comment]
transforms.Normalize([0.5],[0.5])  This way in my settings can work.
